# Generated by Django 6.0.6 on 2026-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoAnalsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('owner', models.CharField()),
                ('repo_name', models.CharField()),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('language_data', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
