# Generated by Django 6.0.6 on 2026-06-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepoAnalsis',
            new_name='RepoAnalysis',
        ),
    ]
